window.videos = [
   {
      title: '',
      url: '',
      duration: '',
      tags: [],
      event: '',
      date: '',
      speakers: '',
      language: '',
      phash: '',
   },
      {
      title: 'db_validation',
      url: '',
      duration: '',
      tags: ['ruby'],
      event: 'Winter SaintP Ruby Meetup 2019',
      date: '2019-02-16',
      speakers: ['Женя Дёмин'],
      language: 'ru',
      phash: '',
   },
   {
      title: 'deploy feature branches on demand',
      url: '',
      duration: '',
      tags: ['ruby'],
      event: 'Winter SaintP Ruby Meetup 2019',
      date: '2019-02-16',
      speakers: ['Сергей Приходько'],
      language: 'ru',
      phash: '',
   },
      {
      title: 'ADT',
      url: '',
      duration: '',
      tags: ['ruby'],
      event: 'Winter SaintP Ruby Meetup 2019',
      date: '2019-02-16',
      speakers: ['Никита Шильников'],
      language: 'ru',
      phash: '',
   },
      {
      title: 'table_sync панельная дискуссия',
      url: '',
      duration: '',
      tags: ['ruby'],
      event: 'a',
      date: '2019-02-16',
      speakers: ['Рустам Ибрагимов'],
      language: 'ru',
      phash: '',
   },
      {
      title: 'Intro to Node',
      url: '',
      duration: '',
      tags: ['ruby'],
      event: 'Winter SaintP Ruby Meetup 2019',
      date: '2019-02-16',
      speakers: ['Вова Смышляев'],
      language: 'ru',
      phash: '',
   },
         {
      title: 'Rails project Arkency way',
      url: '',
      duration: '',
      tags: ['ruby'],
      event: 'Winter SaintP Ruby Meetup 2019',
      date: '2019-02-16',
      speakers: ['Иван Шаматов'],
      language: 'ru',
      phash: '',
   },
         {
      title: 'Service architecture in practice',
      url: '',
      duration: '',
      tags: ['ruby'],
      event: 'Winter SaintP Ruby Meetup 2019',
      date: '2019-02-16',
      speakers: ['Антон Давыдов'],
      language: 'ru',
      phash: '',
   },
	{
		title: 'Дмитрий Павлов, Антон Бевзюк, Domain Driven Design. Как писать простой код для сложных систем?',
		duration: '',
		url: 'https://www.youtube.com/watch?v=SpLJq7OAIQ0',
		tags: ['ddd'],
		event: 'AgileDays 2016',		
		date: '2016-03',
		speakers: ['Дмитрий Павлов', 'Антон Бевзюк'],
		language: 'ru',
		phash: '',
	},
 {
   "title": "Дмитрий Павлов, Антон Бевзюк, Domain Driven Design. Как писать простой код для сложных систем?",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=SpLJq7OAIQ0&list=PLk8AWaxHcq7sJz5h0A30LbhNlxppMPONL&index=26",
   "tags": "",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Дмитрий Грибов, Трава и грибы как средства управления разработкой",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=FNAivcnQ4l0&list=PLk8AWaxHcq7sJz5h0A30LbhNlxppMPONL&index=25",
   "tags": "",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Александр Бындю, Андрей Шапиро, Пять самых важных составляющих процесса выпуска продуктов",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=oEPIL60nw6g&list=PLk8AWaxHcq7sJz5h0A30LbhNlxppMPONL&index=14",
   "tags": "",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Максим Цепков, Действуй, опираясь на ценности, а не просто применяй инструменты!",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=_VZPaN9YHWk&list=PLk8AWaxHcq7sJz5h0A30LbhNlxppMPONL&index=1",
   "tags": "",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Магомед Яндиев, Качественные исследования, или как не потратить рерсурсы на то, что никому не нужно",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=NlITAUUS34Y&index=7&list=PLk8AWaxHcq7sJz5h0A30LbhNlxppMPONL",
   "tags": "",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Денис Тучин - Пользовательские истории в Agile-проектах",
   "duration": "",
   "url": "https://youtu.be/edLf9MV4LbE?list=PLu7pKL8OAoRQ-umtE0Mc7NE4VEx2npmwE",
   "tags": "",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Impact Mapping",
   "duration": "",
   "url": "http://blog.byndyu.ru/2014/12/impact-mapping.html",
   "tags": "",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Discovery Kanban для управления беклогом Scrum-команды",
   "duration": "",
   "url": "http://2016.secr.ru/program/submitted-presentations/using-discovery-kanban-for-scrum-teams-backlog-management",
   "tags": "",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Шаблонный метод",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=MEeMRlaI3u8",
   "tags": "software design",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Лекция 1. Введение в Highload",
   "duration": "",
   "url": "http://www.youtube.com/watch?v=sMiHHFTB5hg",
   "tags": "highload",
   "event": "mail.ru",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Лекция 2. Сетевая подсистема",
   "duration": "",
   "url": "http://www.youtube.com/watch?t=824&v=fI2S8zOWs9I",
   "tags": "highload",
   "event": "mail.ru",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Лекция 3. Протокол HTTP и веб-оптимизация",
   "duration": "",
   "url": "http://www.youtube.com/watch?v=v7wMDH7R7nI",
   "tags": "highload",
   "event": "mail.ru",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Лекция 4. Масштабирование нагрузки",
   "duration": "",
   "url": "http://www.youtube.com/watch?v=0Im7ArJvV6Y",
   "tags": "highload",
   "event": "mail.ru",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Лекция 5. Оперативная память",
   "duration": "",
   "url": "http://www.youtube.com/watch?v=AO8bzpXTRBE",
   "tags": "highload",
   "event": "mail.ru",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Лекция 6. Базы данных и дисковая подсистема",
   "duration": "",
   "url": "http://www.youtube.com/watch?v=zbiAQrkgNJc",
   "tags": "highload",
   "event": "mail.ru",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Лекция 7. Типовые архитектурные решения",
   "duration": "",
   "url": "http://www.youtube.com/watch?v=af_UkpkyJV8",
   "tags": "highload",
   "event": "mail.ru",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Масштабируемая конфигурация nginx, Игорь Сысоев (Nginx)",
   "duration": "",
   "url": "https://vimeo.com/117154512",
   "tags": "highload",
   "event": "Hiload++ 2014",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "HighLoad для начинающих, Обухов Дмитрий (Mail.RU)",
   "duration": "",
   "url": "https://vimeo.com/117154388",
   "tags": "highload",
   "event": "Hiload++ 2014",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Тестирование в Mail Ru",
   "duration": "",
   "url": "http://www.youtube.com/watch?v=LQVACx-O49s",
   "tags": "qa",
   "event": "HighLoad++ 2012.",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Прямая трансляция Я.Субботника по фронтенду",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=8GRtCC3lVN0",
   "tags": "frontend",
   "event": "Яндекс",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Облако в Badoo год спустя-работа над ошибками, Юрий Насретдинов (Badoo",
   "duration": "",
   "url": "https://vimeo.com/123424250",
   "tags": "",
   "event": "Hiload++ 2014",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Надежная раздача видео минимальными средствами, Потапов Евгений (Сумма АйТи)",
   "duration": "",
   "url": "https://vimeo.com/123424285",
   "tags": "",
   "event": "Hiload++ 2014",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Как правильно тестировать приложения",
   "duration": "",
   "url": "",
   "tags": "",
   "event": "HighLoad++ 2012",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Фреймворк для обработки трафика на 10 Gbit/s",
   "duration": "",
   "url": "http://www.youtube.com/watch?v=2WWkZyBom3w",
   "tags": "",
   "event": "Highload++ 2012",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Упрощай и властвуй ( Rails )",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=OslIZ3BHz8I",
   "tags": "",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "HappyDev'15 - Практика применения подходов DDD и CQRS в Ruby-проектах (Руслан Гатиятов)",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=nm9bx-yb4OE",
   "tags": "",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Проблемы использования постоянных соединений.",
   "duration": "",
   "url": "http://www.youtube.com/watch?v=7N3Ro4fa-30",
   "tags": "",
   "event": "Highload++ 2012",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Лекция. Демонстрации",
   "duration": "",
   "url": "https://youtu.be/KBjt2rpv7Oo",
   "tags": "",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Видеохостинг. Что за зверь и для чего он нужен?",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=jk-Lf39HtBQ",
   "tags": "hiload",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Grafite - Как построить миллион графиков",
   "duration": "",
   "url": "https://events.yandex.ru/lib/talks/1122/",
   "tags": "",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Лекция. Скрам",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=25mpNM_w5cc",
   "tags": "",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Руслан Гатиятов – Путь от DB driven разработки к domain driven (DDD)",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=_eM8LcjBWQg&feature=youtu.be",
   "tags": "",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Marionette + Browserify",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=7bGWuyuLK_4",
   "tags": "frontend",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Лекция. Обзор спринта",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=2aLNc-_2wQQ",
   "tags": "",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "О чем никто не говорит, а Google не находит? - нюансы Severity и Priority",
   "duration": "",
   "url": "https://vimeo.com/131272380",
   "tags": "",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Coub: как мы строили аналитическую платформу на несколько миллиардов со",
   "duration": "",
   "url": "https://vimeo.com/117154386",
   "tags": "",
   "event": "Hiload++ 2014",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Продвинутая отладка JavaScript с помощью Сhrome Dev Tools, ",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=Zu3SVmYnFFw",
   "tags": "frontend",
   "event": "Frontend Dev Conf",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "адры решают все, или стриминг видео, Александр Тоболь (Одноклассники",
   "duration": "",
   "url": "https://vimeo.com/123424140",
   "tags": "",
   "event": "Hiload++ 2014",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Zabbix и распределенный мониторинг тысяч серверов, Алексей Владышев (Zabbix. (RootConf 2009)",
   "duration": "",
   "url": "https://vimeo.com/122208875",
   "tags": "",
   "event": "RootConf 2009",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Тестируем инфраструктуру как код",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=kQGeTAVmt24",
   "tags": "",
   "event": "Root Conf 2015",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Прием платежей в Badoo - взгляд изнутри",
   "duration": "",
   "url": "",
   "tags": "",
   "event": "Hiload++ 2014",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Использование асинхронной очереди сообщений",
   "duration": "",
   "url": "https://vimeo.com/101783151",
   "tags": "",
   "event": "Hiload++ 2013",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Инженерный дзен. Непрерывные изменения, Александр Титов (Skype)",
   "duration": "",
   "url": "https://vimeo.com/117462309",
   "tags": "",
   "event": "Hiload++ 2014",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Docker в Badoo: от восторгов к внедрению",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=jjNjAxX61F4",
   "tags": "администрирование",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Сказ о том, как инверсия зависимостей к DDD привела",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=8KBbJcd-PEA",
   "tags": "software design",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "CodeFest 2012. Георгий Баркан. Как научиться делать продукт для пользователей?",
   "duration": "0,5",
   "url": "https://www.youtube.com/watch?v=x9hP4Bm_xqs",
   "tags": "управление проектами",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "CodeFest 2012. Никита Филиппов. Типичные ошибки внедрения Lean и Agile",
   "duration": "1",
   "url": "https://www.youtube.com/watch?v=rdvazcwdmV4",
   "tags": "управление проектами",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Оптимизация затрат на отказоустойчивость",
   "duration": "",
   "url": "http://www.youtube.com/watch?v=JN07rcvRx-M",
   "tags": "",
   "event": "FailOverConference",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Почему не стоит использовать MongoDB",
   "duration": "",
   "url": "http://profyclub.ru/docs/167",
   "tags": "database",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Как снизить нагрузку на высокопосещаемый проект?",
   "duration": "",
   "url": "http://www.youtube.com/watch?v=wed7bLt7X34&list=PLzPivwyXljVXphkuvNPsw4DivvOcdNViE",
   "tags": "",
   "event": "FailOverConference",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "ПРИНЦИПЫ ПОСТРОЕНИЯ РАСПРЕДЕЛЕННЫХ БАЗ ДАННЫХ",
   "duration": "",
   "url": "",
   "tags": "",
   "event": "Rails Club Spring 2015",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Разработка веб-сервисов",
   "duration": "",
   "url": "http://www.youtube.com/playlist?list=PLrCZzMib1e9psjLhQIsZ-PgrHXIyCOq05",
   "tags": "",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Тестирование ПО",
   "duration": "",
   "url": "http://www.youtube.com/playlist?list=PLrCZzMib1e9pDKLsabJYuODdVJrHYc4Jd",
   "tags": "",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Near-realtime аналитика событий в высоконагруженном проекте (Александр Крашенинников, Badoo)",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=3XJhBRiVKW8",
   "tags": "",
   "event": "Highload++ 2015",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "«Как мы сделали ровную балансировку нагрузки на фронтенд-кластере», доклад Юрия youROCK Насретдинова",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=tDU-67wRvgc",
   "tags": "Highload",
   "event": "Highload++ 2015",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "«Docker в работе: взгляд на его использование в Badoo через год», доклад Антона banuchka Турецкого",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=UgUuF_qZmWc",
   "tags": "Highload",
   "event": "Highload++ 2015",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": " «Эволюция клиентской разработки от веба ко „всеобщей мобилизации“ или mobile first на примере Badoo», доклад Павла Довбуша",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=2ufFXMrzXRQ",
   "tags": "Highload",
   "event": "Highload++ 2015",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Ruby Микросервисы и мутабельность и АB тесты",
   "duration": "0,5",
   "url": "http://railsclub.ru/devconf2015.html",
   "tags": "Ruby/Rails",
   "event": "DevConf 2015",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Эксплуатация RoR проектов",
   "duration": "0,8",
   "url": "http://railsclub.ru/devconf2015.html",
   "tags": "Ruby/Rails",
   "event": "DevConf 2015",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Правильная работа с часовыми поясами в Rails-приложении ",
   "duration": "0,1",
   "url": "http://railsclub.ru/devconf2015.html",
   "tags": "Ruby/Rails",
   "event": "DevConf 2015",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "EventMachine или \"Что делать, если вы соскучились по callback-ам?\" ",
   "duration": "0,5",
   "url": "http://railsclub.ru/devconf2015.html",
   "tags": "Ruby/Rails",
   "event": "DevConf 2015",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Создание Быстрых, отказоустойчивых сервисов на EventMachine ",
   "duration": "",
   "url": "",
   "tags": "Ruby/Rails",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "ИЩЕМ ГДЕ И ПОЧЕМУ PRODUCTION ПРИЛОЖЕНИЕ ТОРМОЗИТ",
   "duration": "",
   "url": "",
   "tags": "Ruby/Rails",
   "event": "Rails Club Spring 2015",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "СБОР И ОБРАБОТКА СТАТИСТИКИ О ПРОЧТЕНИЯХ КНИГ",
   "duration": "",
   "url": "",
   "tags": "Ruby/Rails",
   "event": "Rails Club Spring 2015",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "RUBY OBJECT MAPPER: REVOLUTION",
   "duration": "",
   "url": "",
   "tags": "Ruby/Rails",
   "event": "Rails Club Spring 2015",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Почему юнит тесты не работают. История большого проекта",
   "duration": "",
   "url": "http://msk15.agiledays.ru/members/profile/1135/#report-59",
   "tags": "",
   "event": "Agile days 2015",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "I’LL SIDEKIQ YOU, CARL!",
   "duration": "",
   "url": "",
   "tags": "Ruby/Rails",
   "event": "Rails Club Spring 2015",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "(Не)безопасный Frontend",
   "duration": "",
   "url": "",
   "tags": "",
   "event": "Frontend Conf 2015",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Chef по обе стороны Bamboo",
   "duration": "",
   "url": "",
   "tags": "",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Как сделать кроссплатформенное десктопное приложение на базе веб-технологий",
   "duration": "",
   "url": "http://rootconf.ru/2015/abstracts/1818",
   "tags": "",
   "event": "RootConf 2015",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Эволюция службы эксплуатации Spotify",
   "duration": "",
   "url": "",
   "tags": "",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Путь DevOps в Parallels",
   "duration": "",
   "url": "",
   "tags": "",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Использование haproxy/iptables+etcd+confd для автоматического service discovery в переменчивых сетях",
   "duration": "",
   "url": "",
   "tags": "",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "OpenStack: от enterprise к сервис-провайдеру",
   "duration": "",
   "url": "",
   "tags": "",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Платформа для поставки счастья в команду QA",
   "duration": "",
   "url": "",
   "tags": "",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Правильное обнаружение проблем с помощью Zabbix",
   "duration": "",
   "url": "",
   "tags": "",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Мониторинг в высоконагруженных (и не только) проектах: сравнительный анализ существующих решений",
   "duration": "",
   "url": "",
   "tags": "",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Единая платформа для сайта и приложений Медузы",
   "duration": "",
   "url": "",
   "tags": "",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Как построить идеальный процесс локализации продукта и почему делать этого не нужно",
   "duration": "",
   "url": "",
   "tags": "",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Реалтайм статистика скорости работы нативных и веб-приложений у реальных пользователей",
   "duration": "",
   "url": "",
   "tags": "",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Обзор архитектуры и подсистем деплоя и мониторинга. Как инженеры делают систему прозрачной для разработки",
   "duration": "",
   "url": "http://rootconf.ru/2015/abstracts/1763",
   "tags": "",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Мейкап и контроль качества верстки",
   "duration": "",
   "url": "",
   "tags": "",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Построение надежных, гибких, расширяемых систем в реальном мире»",
   "duration": "",
   "url": "http://www.youtube.com/watch?v=N9gPub0Eoss&index=10&list=PLzPivwyXljVXphkuvNPsw4DivvOcdNViE",
   "tags": "",
   "event": "FailOverConference",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Отказоустойчивый код» на конференции FailOverConference",
   "duration": "",
   "url": "http://www.youtube.com/watch?v=fkzvCq4_b1c&index=9&list=PLzPivwyXljVXphkuvNPsw4DivvOcdNViE",
   "tags": "",
   "event": "FailOverConference",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Highload не кусается",
   "duration": "",
   "url": "http://www.youtube.com/watch?v=CsX-IrxMUb0",
   "tags": "",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "От CMS к Highload: работа с backend, Александр Каскевич, Алексей Сазанов",
   "duration": "",
   "url": "http://www.youtube.com/watch?v=7ehfOqtsiZ4",
   "tags": "",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Как правильно тестировать приложения",
   "duration": "",
   "url": "http://www.youtube.com/watch?v=lLNsdT0_KxA",
   "tags": "",
   "event": "Highload++ 2012",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Цикл разработки, визуальный деплой, автоматизация и интернационализация",
   "duration": "",
   "url": "http://www.youtube.com/watch?v=LtnKMlX6V4Q",
   "tags": "",
   "event": "Highload++ 2012",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Проникновение на рынок высоко-масштабируемых систем и услуг",
   "duration": "",
   "url": "http://www.youtube.com/watch?v=e2M00x4Pr5o",
   "tags": "",
   "event": "Highload++ 2012",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Ultralow Latency Highload, Юрий Гущин",
   "duration": "",
   "url": "http://www.youtube.com/watch?v=gfdAfhSM724",
   "tags": "",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "75 млн. пользователей - пишем неблокируемый сервер",
   "duration": "",
   "url": "http://www.youtube.com/watch?v=AVht3ReHUJI",
   "tags": "",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "No Guts, NoSQL, No Glory",
   "duration": "",
   "url": "http://www.youtube.com/watch?v=Cj6rO5katOo",
   "tags": "",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Масштабируемый DevOps, Александр Колесень",
   "duration": "",
   "url": "http://www.youtube.com/watch?v=c6W84QhZx2s",
   "tags": "",
   "event": "Highload++ 2012",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Оптимизация одного из топовых приложений для социальной сети ВКонтакте: 1000 запросов в секунду на Rails",
   "duration": "",
   "url": "http://profyclub.ru/docs/73",
   "tags": "",
   "event": "Highload++ 2012",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "как перестать отлаживать асинхронные вызовы и начать жить",
   "duration": "",
   "url": "",
   "tags": "",
   "event": "Frontend Dev Conf 2015",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "The Illusion of Time. When 60 sec is not 1 minute",
   "duration": "",
   "url": "",
   "tags": "",
   "event": "Frontend Dev Conf 2015",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Медленный JS: сеанс черной магии с ее разоблачением",
   "duration": "",
   "url": "",
   "tags": "",
   "event": "Frontend Dev Conf 2015",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Удаленная разработка фронтенда в командной строке",
   "duration": "",
   "url": "",
   "tags": "frontend",
   "event": "Frontend Dev Conf 2015",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "I knew there had to be a better way to build movile app",
   "duration": "",
   "url": "",
   "tags": "",
   "event": "Frontend Dev Conf 2015",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Разрушаем вавилонскую башню www с помощью веб-компонент",
   "duration": "",
   "url": "",
   "tags": "",
   "event": "Frontend Dev Conf 2015",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Артем Сущев «ember.js - инструмент нового поколения»",
   "duration": "",
   "url": "https://www.youtube.com/user/FrontendDevConf",
   "tags": "",
   "event": "Frontend Dev Conf",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "API first approach for frontend developers, Роман Бугаев",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=ZR3lQ5bb5lY",
   "tags": "",
   "event": "Frontend Dev Conf",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Автоматизация фронтенда — сегодня и завтра, Роберт Харитонов",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=Fe5fW-WtQSI",
   "tags": "frontend",
   "event": "Frontend Dev Conf",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Как верстать сайты быстрее, чем их рисуют, Юрий Артюх",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=tdRuZfZW99A",
   "tags": "",
   "event": "Frontend Dev Conf",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Визуальное мышление в разработке, Наталья Ядренцева",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=ekOivWLquCY",
   "tags": "",
   "event": "Frontend Dev Conf",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Offline Web Applications, Jan Jongboom",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=AbixY3W8ayo",
   "tags": "",
   "event": "Frontend Dev Conf",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "React, или как начать жить проще, Александр Соловьев",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=YJNUK0EA_Jo",
   "tags": "",
   "event": "Frontend Dev Conf",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Testing web APIs, Jakob Mattsson",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=mlnUK_6K7Qs",
   "tags": "",
   "event": "Frontend Dev Conf",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Эффективное управление асинхронным кодом в JavaScript",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=FyCkQuF3-qM",
   "tags": "",
   "event": "Frontend Dev Conf",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Научный дизайн",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=S6PQaiRl98c",
   "tags": "",
   "event": "Frontend Dev Conf",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Writing RESTful web services using Node.js",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=DomgE7AzjWc",
   "tags": "",
   "event": "Frontend Dev Conf",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Zombiecode",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=rX5_UPVouhU",
   "tags": "",
   "event": "Frontend Dev Conf",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Full stack JavaScript -- the folly of choice",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=-oQHOo0VSkw",
   "tags": "",
   "event": "Frontend Dev Conf",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Rails Conf 2013 Front-end Testing for Skeptics By Luke Francl",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=9GO7XGmv5gk",
   "tags": "Ruby/Rails",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Фронтенд без багов. Путь фичи: от идеи через разработку к продакшену",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=7W5ZzrACCkA",
   "tags": "frontend",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "1. «StatsCollector, или «Мама! Он и меня посчитал!»».\nСтарынин Валерий, PHP разработчик отдела BI, Badoo.",
   "duration": "",
   "url": "http://habrahabr.ru/company/badoo/blog/238153/",
   "tags": "",
   "event": "Видео докладов с конференции DevConf 2014",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "2. «Пишем функциональное, надежное и быстрое веб-приложение на Go».\nДмитрий dvyukov Вьюков, разработчик, Google.",
   "duration": "",
   "url": "http://habrahabr.ru/company/badoo/blog/238153/",
   "tags": "",
   "event": "Видео докладов с конференции DevConf 2014",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "5. «Pinboard + pinba. Как организовать мониторинг сотни проектов».\nИльяс muxx Салихов, CTO в Интаро.",
   "duration": "",
   "url": "http://habrahabr.ru/company/badoo/blog/238153/",
   "tags": "",
   "event": "Видео докладов с конференции DevConf 2014",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Как правильно разрабатывать API с поддержкой обратной совместимости. Семинар в Яндексе",
   "duration": "",
   "url": "http://habrahabr.ru/company/yandex/blog/237459/",
   "tags": "",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Как мы тестируем CSS-регрессии с Gemini. Доклад на BEMup в Яндексе",
   "duration": "",
   "url": "http://habrahabr.ru/company/yandex/blog/238323/",
   "tags": "",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Протоколы уровня приложения в браузере, Илья Кутуков (Parallels).mp4",
   "duration": "",
   "url": "https://vimeo.com/123424329",
   "tags": "",
   "event": "Hiload++ 2014",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "То, что вы хотели знать о HandlerSocket, но не смогли нагуглить, Сергей Аверин",
   "duration": "",
   "url": "https://vimeo.com/123424290",
   "tags": "",
   "event": "Hiload++ 2014",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Использование Hadoop в Badoo, Валерий Старынин (Badoo)",
   "duration": "",
   "url": "https://vimeo.com/123424247",
   "tags": "",
   "event": "Hiload++ 2014",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Изменение процесса разработки и тестирования, Владислав Чернов (Badoo)",
   "duration": "",
   "url": "https://vimeo.com/123424136",
   "tags": "",
   "event": "Hiload++ 2014",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Partly cloudy. Построение отказоустойчивых систем в AWS минимальными средств",
   "duration": "",
   "url": "https://vimeo.com/123424135",
   "tags": "",
   "event": "Hiload++ 2014",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Memcached-инъекции-они существуют и работают, Иван Новиков (ONsec)",
   "duration": "",
   "url": "https://vimeo.com/123424096",
   "tags": "",
   "event": "Hiload++ 2014",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Балансируем трафик локально и глобально. Защищаемся от атак. Оптимизируем передачу данных. (RootConf 2009)",
   "duration": "",
   "url": "https://vimeo.com/122208890",
   "tags": "",
   "event": "RootConf 2009",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Как устроена MySQL репликация, Андрей Аксенов (Sphinx)",
   "duration": "",
   "url": "https://vimeo.com/118337964",
   "tags": "database",
   "event": "Hiload++ 2014",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Большая книга рецептов или часто задаваемые вопросы по управлению сложными системами, Александр Титов, Игорь Курочкин (Skype)",
   "duration": "",
   "url": "https://vimeo.com/117462317",
   "tags": "",
   "event": "Hiload++ 2014",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Puppet под нагрузкой, Антон Турецкий (Badoo)",
   "duration": "",
   "url": "https://vimeo.com/117462308",
   "tags": "",
   "event": "Hiload++ 2012",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Ускоряем и разгружаем веб-сервер прозрачно кэшируя на SSD, Станислав Ни",
   "duration": "",
   "url": "https://vimeo.com/117462269",
   "tags": "",
   "event": "Hiload++ 2014",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Клиентские приложения под нагрузкой, Андрей Смирнов (ex-Skype)",
   "duration": "",
   "url": "https://vimeo.com/117462268",
   "tags": "",
   "event": "Hiload++ 2014",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Отказоустойчивый микрокластер своими руками, Виталий Гаврилов (Ленве",
   "duration": "",
   "url": "https://vimeo.com/117154627",
   "tags": "",
   "event": "Hiload++ 2014",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Разработка аналитической системы для высоконагруженного медиа, Олег",
   "duration": "",
   "url": "https://vimeo.com/117154578",
   "tags": "",
   "event": "Hiload++ 2014",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Инструментарий управления разработкой Mail.Ru Group, Александр Горный (Mail.Ru",
   "duration": "",
   "url": "https://vimeo.com/117154463",
   "tags": "",
   "event": "Hiload++ 2014",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Использование memcached и Redis в высоконагруженных проектах, Вячеслав Москаленко",
   "duration": "",
   "url": "https://vimeo.com/117154462",
   "tags": "",
   "event": "Hiload++ 2014",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Асинхронная репликация без цензуры, Олег Царёв (Mail.Ru Group)",
   "duration": "",
   "url": "https://vimeo.com/117154460",
   "tags": "",
   "event": "Hiload++ 2014",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Выбираем поисковик умом головы, Андрей Аксенов (Sphinx)",
   "duration": "",
   "url": "https://vimeo.com/117154436",
   "tags": "",
   "event": "Hiload++ 2014",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Архитектура приложений с использованием MySQL, Петр Зайцев (Percona)",
   "duration": "",
   "url": "https://vimeo.com/117154435",
   "tags": "database",
   "event": "Hiload++ 2014",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Sharding - patterns and antipatterns, Константин Осипов (Mail.ru, Tarantool), Алексей Рыбак (Badoo)",
   "duration": "",
   "url": "https://vimeo.com/117154434",
   "tags": "",
   "event": "Hiload++ 2014",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Анатомия веб-сервиса, Андрей Смирнов (ex-Skype)",
   "duration": "",
   "url": "https://vimeo.com/117154389",
   "tags": "",
   "event": "Hiload++ 2014",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Считаем Рунет, или миллион pps в секунду",
   "duration": "",
   "url": "https://vimeo.com/113249001",
   "tags": "",
   "event": "Hiload++ 2014",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Поиск узких мест в производительности MySQL ботанический определитель,",
   "duration": "",
   "url": "https://vimeo.com/106896258",
   "tags": "database",
   "event": "Hiload++ 2011",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Настройка FreeBSD для обслуживания 100-200 тысяч соединений, Игорь Сысоев (Ngi",
   "duration": "",
   "url": "https://vimeo.com/106896255",
   "tags": "",
   "event": "Hiload++ 2011",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Распределенные системы хранения данных для аналитики Vertica и другие си",
   "duration": "",
   "url": "https://vimeo.com/105424020",
   "tags": "",
   "event": "Hiload++ 2011",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Оптимизатор запросов в MariaDB 10.0 - теперь и без индексов, Сергей Голубчик",
   "duration": "",
   "url": "https://vimeo.com/105424017",
   "tags": "",
   "event": "Hiload++ 2011",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Завалить в один запрос: уязвимости веб-приложений, приводящие к DoS",
   "duration": "",
   "url": "https://vimeo.com/105132049",
   "tags": "",
   "event": "Hiload++",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Архитектура Бегуна - обеспечение High Load & High Availability, Алексадр Румянцев (B",
   "duration": "",
   "url": "https://vimeo.com/101783245",
   "tags": "",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Поисковая система Одноклассники.ру, Алексей Шевчук (Одноклассники)",
   "duration": "",
   "url": "",
   "tags": "",
   "event": "Hiload++ 2012",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Сервер приложений SUP Fabrik, Андрей Шетухин, Игорь Семенов (SUP Fabrik)",
   "duration": "",
   "url": "",
   "tags": "",
   "event": "Hiload++ 2008",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Обзорный доклад о архитектуре статистики LiveInternet, Александр Таксиков",
   "duration": "",
   "url": "",
   "tags": "",
   "event": "Hiload++ 2008",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Специализированные http-демона, Сергей Боченков, Александр Панков",
   "duration": "",
   "url": "",
   "tags": "",
   "event": "Hiload++",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Крупное online-СМИ на примере Gazeta.RU, Expert.RU, Владимир Сошкин (DJEM Solutions)",
   "duration": "",
   "url": "https://vimeo.com/101783122",
   "tags": "",
   "event": "Hiload++ 2008",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Архитектура AdRiver, Всеволод Потапов, Виталий Иванов (Adriver)",
   "duration": "",
   "url": "https://vimeo.com/101783104",
   "tags": "",
   "event": "Hiload++",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Как написать масштабируемую баннерокрутилку, Денис Бирюков (Каванга)",
   "duration": "",
   "url": "https://vimeo.com/101783121",
   "tags": "",
   "event": "Hiload++",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Одно постоянное соединение на все вкладки сайта",
   "duration": "",
   "url": "https://vimeo.com/101783124",
   "tags": "",
   "event": "Hiload++",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Вещание видео на 10 ГБитс, Максим Лапшин (Erlyvideo)",
   "duration": "",
   "url": "https://vimeo.com/95959450",
   "tags": "",
   "event": "Hiload++ 2013",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Документирование вёрстки по-взрослому, Роберт Харитонов",
   "duration": "",
   "url": "https://vimeo.com/95959442",
   "tags": "",
   "event": "Hiload++ 2013",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Разработка поддерживаемых и гибких интерфейсов, Василий Аксёнов",
   "duration": "",
   "url": "https://vimeo.com/95959403",
   "tags": "",
   "event": "РИТ 2013",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Полнотекстовый поиск в PostgreSQL за миллисекунды, О. Бартунов, А. Коротков",
   "duration": "",
   "url": "https://vimeo.com/95317317",
   "tags": "database",
   "event": "Hiload++ 2012",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Как мы храним 60000 событий в секунду, Арсен Мукучян (AdRiver)",
   "duration": "",
   "url": "https://vimeo.com/95315901",
   "tags": "",
   "event": "Hiload++ 2013",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Как Badoo модерирует 1 миллиард фотографий в год, Андрей Гоменюк (Badoo)",
   "duration": "",
   "url": "https://vimeo.com/95315899",
   "tags": "",
   "event": "Hiload++ 2012",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Практика NOSQL в высоконагруженном проекте, Дмитрий Ананьев (Мамба)",
   "duration": "",
   "url": "https://vimeo.com/95313697",
   "tags": "database",
   "event": "Hiload++ 2012",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Mature optimization (Своевременная оптимизация), Carlos Bueno (Facebook)",
   "duration": "",
   "url": "https://vimeo.com/95313692",
   "tags": "",
   "event": "Hiload++ 2013",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Как инженеры компанию создавали от CDNvideo, Ярослав Городецкий",
   "duration": "",
   "url": "https://vimeo.com/80599024",
   "tags": "",
   "event": "Whale Rider 2013",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "AJAX Layout, Олег Илларионов (ВКонтакте)",
   "duration": "",
   "url": "https://vimeo.com/95174804",
   "tags": "",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "100500 требований к продукту, или Как не создать монстра, Кармацкий\n/ Яндекс",
   "duration": "",
   "url": "https://vimeo.com/79665571",
   "tags": "",
   "event": "Whale Rider 2013",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Как устроена облачная компания? Аскар Рахимбердиев (МойСклад)",
   "duration": "",
   "url": "https://vimeo.com/79099923",
   "tags": "",
   "event": "Whale Rider 2013",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Эволюция разработки в Badoo, Алексей Рыбак (Badoo)",
   "duration": "",
   "url": "https://vimeo.com/77200494",
   "tags": "",
   "event": "Whale Rider 2013",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Новая архитектура шардинга MongoDB для обеспечения высокой доступности и более оптимального использования ресурсов",
   "duration": "",
   "url": "",
   "tags": "database",
   "event": "Hiload++ 2014",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "PostgreSQL: Ups, DevOps...",
   "duration": "",
   "url": "",
   "tags": "database",
   "event": "Hiload++ 2014",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Как устроена MySQL-репликация",
   "duration": "",
   "url": "",
   "tags": "database",
   "event": "Hiload++ 2014",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Как мы храним и анализируем большой социальный граф",
   "duration": "",
   "url": "",
   "tags": "",
   "event": "Hiload++ 2014",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Как PostgreSQL работает с диском?",
   "duration": "",
   "url": "https://vimeo.com/123424249",
   "tags": "database",
   "event": "Hiload++ 2014",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Разработка аналитической системы для высоконагруженного медиа",
   "duration": "",
   "url": "",
   "tags": "",
   "event": "Hiload++ 2014",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "SSD для вашей базы данных",
   "duration": "",
   "url": "https://vimeo.com/117154387",
   "tags": "database",
   "event": "Hiload++ 2014",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Тестируем производительность распределенных систем хранения данных,",
   "duration": "",
   "url": "https://vimeo.com/123424287",
   "tags": "hardware",
   "event": "Hiload++ 2014",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Партицирование и миграции данных на примере PostgreSQL",
   "duration": "",
   "url": "",
   "tags": "database",
   "event": "Hiload++ 2014",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Принципы работы брокера сообщений RabbitMQ",
   "duration": "",
   "url": "",
   "tags": "",
   "event": "Hiload++ 2014",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Шардинг в MongoDB",
   "duration": "",
   "url": "",
   "tags": "database",
   "event": "Hiload++ 2014",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Игры с виртуализацией в JavaScript, или как я переписал эмулятор",
   "duration": "",
   "url": "",
   "tags": "",
   "event": "Hiload++ 2014",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Кластеризация BigData на примере подарков в ОК",
   "duration": "",
   "url": "",
   "tags": "",
   "event": "Hiload++ 2014",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Continuous Delivery, или волшебная кнопка для релизов по запросу",
   "duration": "",
   "url": "",
   "tags": "",
   "event": "Hiload++ 2014",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "SDCH, или новые подходы увеличения производительности за счет сжатия отправляемого трафика",
   "duration": "",
   "url": "",
   "tags": "",
   "event": "Hiload++ 2014",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Как обслужить 60 миллионов абонентов?",
   "duration": "",
   "url": "",
   "tags": "",
   "event": "Hiload++ 2014",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "PostgreSQL: масштабирование в моде. От стартапа к уровню международной компании Zalando",
   "duration": "",
   "url": "",
   "tags": "database",
   "event": "Hiload++ 2014",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Как считать и анализировать сотни гигабит трафика в секунду, не тратясь на Hadoop и не парся логи",
   "duration": "",
   "url": "",
   "tags": "",
   "event": "Hiload++ 2014",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Архитектура бэкенда карт sputnik.ru",
   "duration": "",
   "url": "",
   "tags": "",
   "event": "Hiload++ 2014",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "!sync: асинхронное взаимодействие",
   "duration": "",
   "url": "",
   "tags": "",
   "event": "Hiload++ 2014",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "1Hippeus - zero-copy messaging по законам Спарты!",
   "duration": "",
   "url": "",
   "tags": "",
   "event": "Hiload++ 2014",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Инфраструктура – это часть вашего приложения",
   "duration": "",
   "url": "",
   "tags": "",
   "event": "Hiload++ 2014",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "DDoS-атаки в России в 2014 годy: UDP-пакеты салом не пахнут",
   "duration": "",
   "url": "",
   "tags": "",
   "event": "Hiload++ 2014",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Применение статистических методов и инструментов для анализа производительности систем",
   "duration": "",
   "url": "",
   "tags": "",
   "event": "Hiload++ 2014",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "5 причин, по которым MongoDB является ведущей NoSQL СУБД",
   "duration": "",
   "url": "",
   "tags": "database",
   "event": "Hiload++ 2014",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Тестирование с большей пользой",
   "duration": "",
   "url": "",
   "tags": "",
   "event": "Hiload++ 2014",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Highway to Continuous Integration",
   "duration": "",
   "url": "",
   "tags": "",
   "event": "Hiload++ 2014",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Профилирование и оптимизация производительности Ruby-кода",
   "duration": "",
   "url": "http://www.youtube.com/watch?v=7N3Ro4fa-30",
   "tags": "Ruby",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Как не угробить архитектуру сразу же? Видео с лекции Евгения Кривошеева",
   "duration": "",
   "url": "http://habrahabr.ru/company/jugru/blog/261379/",
   "tags": "",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Building Decoupled Applications - Sam Saccone",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=882lVlCoRsY",
   "tags": "",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Ruby Midwest 2011 - Keynote: Architecture the Lost Years by Robert Martin",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=WpkDN78P884",
   "tags": "",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "SECON 2012 - Александр Цветков. Использование неблокирующих веб-серверов в highload проектах",
   "duration": "",
   "url": "http://www.youtube.com/watch?v=lDl-oD_rQ60",
   "tags": "",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Стабильность проекта в условиях непрерывной интеграции",
   "duration": "",
   "url": "http://www.youtube.com/watch?v=XYWF7bMNcq4&index=6&list=PLzPivwyXljVXphkuvNPsw4DivvOcdNViE",
   "tags": "",
   "event": "FailOverConference",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Новые возможности репликации в MySQL 5.6",
   "duration": "",
   "url": "http://www.youtube.com/watch?v=auqT4hZ4XoI&index=8&list=PLzPivwyXljVXphkuvNPsw4DivvOcdNViE",
   "tags": "database",
   "event": "FailOverConference",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "HighLoad++ 2012. Язык программирования Go от Google",
   "duration": "",
   "url": "",
   "tags": "",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Invisible Code by Martin Kleppe at JSConf Budapest 2015",
   "duration": "",
   "url": "https://www.youtube.com/watch?list=PLFZ5NyC0xHDaaTy6tY9p0C0jd_rRRl5Zm&v=T3xMyZH93i8",
   "tags": "",
   "event": "JSConf Budapest 2015",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "4. «Codeception — тестируем с человеческим лицом».\nМихаил Боднарчук — автор Codeception, веб разработчик из Киева.",
   "duration": "",
   "url": "http://habrahabr.ru/company/badoo/blog/238153/",
   "tags": "",
   "event": "DevConf 2014",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "6. «Go: аналитика Рунета в реальном времени».\nАндреенко Артём miolini, инженер, компания Openstat (Spylog)",
   "duration": "",
   "url": "http://habrahabr.ru/company/badoo/blog/238153/",
   "tags": "",
   "event": "DevConf 2014",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Продвинутая отладка JavaScript с помощью Сhrome Dev Tools",
   "duration": "",
   "url": "https://youtu.be/Zu3SVmYnFFw\nhttp://frontender.info/chrome-developer-tools/",
   "tags": "frontend",
   "event": "FrontendDevConf",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Сергей Бережной Frontend-Developer Yandex",
   "duration": "",
   "url": "https://events.yandex.ru/lib/people/34/",
   "tags": "frontend, методологии",
   "event": "Yandex",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Что появится в JS (Что интересного готовит нам W3C)",
   "duration": "",
   "url": "https://events.yandex.ru/lib/talks/1508/",
   "tags": "frontend",
   "event": "Yandex",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "#QA Андрей Солнцев. Codeborne. Экономически эффективный процесс тестирования",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=PZq_J1AuSL0",
   "tags": "qa",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Николай Чабановский. Внутри Stack Overflow",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=Y8_1541yl3o",
   "tags": "управление проектами",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "#Frontend Виталий Харисов и Иван Воищев. От БЭМ-методологии до Мануфактуры проектов",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=icAwYLLb3Qs",
   "tags": "frontend",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "#Блиц. Дмитрий Калугин-Балашов. Backend: Полнотекстовый поиск в Почте Mail.Ru",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=mTRSx3NQGZ8",
   "tags": "backend",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "#PM Харитон Матвеев. Skyeng. 20 млн.$ за два года с нуля, или как мы делаем нужный людям продукт",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=yx2k_Z9wjac",
   "tags": "управление проектами",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "#PM Дмитрий Сысоев. Saintlab. Чего стоит сделать стартап",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=rzyovT6mv7c",
   "tags": "управление проектами",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "#Квартирник Виталий Харисов, Яндекс. Собираем проект на БЭМ из готовых компонентов",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=9bFbuVGTdCo",
   "tags": "frontend",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "#Квартирник Татьяна Писчасова. 2ГИС. Мир без тестировщиков. Миф или реальность?",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=9Pg2VKqupG4",
   "tags": "qa",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "#Квартирник Алексей Анисимов. ForFunDev, Алексей Романенко. Flamp. Мотивация разработчиков",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=ArtKwDYz_b4",
   "tags": "управление проектами",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "#Квартирник Michael Yarichuk. Hibernating Rhinos. Polyglot Persistence",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=vQWN4-poWiE",
   "tags": "управление проектами",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "#PM Максим Цепков. CUSTIS. Развитие управления проектами и критериев качества в ИТ",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=PayRtw122UU",
   "tags": "управление проектами",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "#PM Максим Дорофеев. mnogosdelal.ru. Тупняк как чума 21 века и что с этим делать",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=RbOkgLa1XjM",
   "tags": "управление проектами",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "#PM Егор Данилов. ivi.ru. Growth hacking своими руками – поиск ключа к росту продукта",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=Iky6vMB4wL4",
   "tags": "управление проектами",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "#PM Michael Yarichuk. Hibernating Rhinos. Эффективная, вовлеченная команда энтузиастов.",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=7JAaCq5Wb1s",
   "tags": "управление проектами",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "#Backend Роман Ивлиев. Банки.ру. Как banki.ru пережил утроение нагрузки за неделю",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=tFdEi5ahUkA",
   "tags": "hiload",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "#Backend Дмитрий Пацура. Phalcon/Zephir. Сладкое будущее: Phalcon и Zephir",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=jbsl08Ya3Hg",
   "tags": "",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "#Backend Ренат Ахмеров. Mirantis. Построение облачных процессов с помощью Mistral",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=TBfFSf8Hooo",
   "tags": "",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "#Backend Василий Васильков. Ecwid. Дорога к микросервисной архитектуре",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=vA7nnGwCnTY",
   "tags": "",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "#Backend Иван Ремизов. Parallels. Сверхоптимизация кода на Python",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=K3qL3NqZDcE",
   "tags": "",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "#Backend Олег Бартунов. ГАИШ МГУ. NoSQL для PostgreSQL: Jsquery — язык запросов",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=aVyFEOZy9Y4",
   "tags": "",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "#Mobile Юрий Буянов. Одноклассники. Комфортная разработка мобильных проектов.",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=cfSta59E0BU",
   "tags": "mobile",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "#Mobile Лев Толмачев. Яндекс. Мультиплатформенная синхронизация структурированных данных.",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=bLktPEN5eLA",
   "tags": "mobile",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "# Mobile Ярослав Храмов. Booking.com. Getting it Booking right.",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=-OOW6blgHq4",
   "tags": "mobile",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "#Блиц Кирилл Кайсаров. 2ГИС. Frontend: Путешествие в мир модульных загрузчиков",
   "duration": "0,3",
   "url": "https://www.youtube.com/watch?v=-VVInOYIOUQ",
   "tags": "mobile",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "#Блиц Денис Колегов. F5 Networks. QA: Базовое тестирование защищенности веб-приложений в рамках QA",
   "duration": "0,3",
   "url": "https://www.youtube.com/watch?v=l3vYJ3FuQj4",
   "tags": "qa",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "#Квартирник Алексей Медведчиков. 2ГИС. Deployment best practices - Как хорошо накатить?",
   "duration": "1",
   "url": "https://www.youtube.com/watch?v=htRexSt2zwc",
   "tags": "devops",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "#Backend Николай Крапивный. Badoo. Все о бекенде мобильных приложений Badoo",
   "duration": "0,5",
   "url": "https://www.youtube.com/watch?v=TRht7k16RQk",
   "tags": "mobile",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "#Backend Alexander Demidko. Metamarkets. Аналитика над петабайтами в реальном времени",
   "duration": "0,5",
   "url": "https://www.youtube.com/watch?v=bAGDrGmuUSc",
   "tags": "",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "#Frontend Никита Прокопов. Свободный художник. Функциональное программирование в браузере",
   "duration": "0,6",
   "url": "https://www.youtube.com/watch?v=CohpRapbXqA",
   "tags": "frontend",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "#Frontend Денис Речкунов. Flamp. Изоморфный JavaScript — будущее уже здесь",
   "duration": "0,6",
   "url": "https://www.youtube.com/watch?v=MPGt7Tef83Y",
   "tags": "frontend",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "#Frontend Роман Дворнов. Авито. Инструменты разные нужны, инструменты разные важны",
   "duration": "0,5",
   "url": "https://www.youtube.com/watch?v=HMTc3DERw5c",
   "tags": "frontend",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "#Frontend Денис Радин. Liberty Global. HTML GL - возьмите столько FPS, сколько вам нужно!",
   "duration": "0,6",
   "url": "https://www.youtube.com/watch?v=avZirLpugck",
   "tags": "frontend",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "#Frontend Антон Плешивцев. Aviasales.ru. Лучший frontend-фреймворк, и почему вы его не хотите",
   "duration": "0,6",
   "url": "https://www.youtube.com/watch?v=sHMhprMS6Pw",
   "tags": "frontend",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "#Backend Дмитрий Кукса. Яндекс. Организация процесса регулярной обработки больших объемов данных",
   "duration": "0,6",
   "url": "https://www.youtube.com/watch?v=xeWtaMjTZbQ",
   "tags": "",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "#Backend Алексей Романчук. 2ГИС. Быстрое построение backendов c помощью реактивных потоков",
   "duration": "0,6",
   "url": "https://www.youtube.com/watch?v=N4ojoVsWmbQ",
   "tags": "",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "#Backend Кирилл Скрыган. JetBrains. ReSharper vs Roslyn",
   "duration": "0,5",
   "url": "https://www.youtube.com/watch?v=MvuHBrkZ3c0",
   "tags": "",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "#QA Максим Богуславский. Banki.ru. Идеальный тестдизайн: от Цема Канера до Agile",
   "duration": "0,7",
   "url": "https://www.youtube.com/watch?v=wUJ9mcwuneo",
   "tags": "qa",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "#QA Sathish Gogineni. Badoo. Badoo: Cross platform Mobile Test Automation and Continuos Delivery",
   "duration": "0,6",
   "url": "https://www.youtube.com/watch?v=N0hYSHmRJTQ",
   "tags": "",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "#QA Дмитрий Химион. Performance Lab. Технический долг: взгляд и действия со стороны QA / QC&AT",
   "duration": "1",
   "url": "https://www.youtube.com/watch?v=WlkYHcYckKU",
   "tags": "",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "# QA Николай Абалов. 2ГИС. Автоматизация UI тестирования под Windows и Windows Phone",
   "duration": "0,5",
   "url": "https://www.youtube.com/watch?v=5zhDyxVDSeQ",
   "tags": "",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Александр Бабаев (DevPocket): \"Сервер для самых маленьких\"",
   "duration": "0,3",
   "url": "https://www.youtube.com/watch?v=J9rS4clHX_I",
   "tags": "",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Павел Власов (Ostrovok.ru): \"Мониторинг API Ostrovok.ru\"",
   "duration": "0,3",
   "url": "https://www.youtube.com/watch?v=OJL8ZMEDeAQ",
   "tags": "",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Пётр Русанов (LinguaLeo): \"Кеш, транзакционный лог и проблемы синхронизации\"",
   "duration": "0,3",
   "url": "https://www.youtube.com/watch?v=pDh0vGgzQmM",
   "tags": "",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Иван Белый (Marmalade): \"Marmalade SDK. Что под капотом?\"",
   "duration": "0,6",
   "url": "https://www.youtube.com/watch?v=5SuYJBM_eVc",
   "tags": "",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "В. Биллевич: \"SDK мобильного сервиса. Добавление новой функциональности в приложение\"",
   "duration": "0,5",
   "url": "https://www.youtube.com/watch?v=AkG9sZFWYaM",
   "tags": "",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Александр Феоктистов (Яндекс): \"Как мы сделали Яндекс.Гардероб и не ослепли\"",
   "duration": "0,3",
   "url": "https://www.youtube.com/watch?v=m5ill81pIjQ",
   "tags": "",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Никита Прокопов (Echo): \"Зачем вам нужна Clojure?\"",
   "duration": "0,5",
   "url": "https://www.youtube.com/watch?v=jZI1aZcRHCI",
   "tags": "",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Григорий Никонов: \"Как мы разрабатываем приложения для Windows Phone\"",
   "duration": "0,5",
   "url": "https://www.youtube.com/watch?v=FLuDsJ2N58M",
   "tags": "mobile",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Максим Конев (Arello Mobile): \"Push-уведомления\"",
   "duration": "0,6",
   "url": "https://www.youtube.com/watch?v=T1yDYDGE3h0",
   "tags": "mobile",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Артём Чернышёв (2ГИС): \"Пути миграции перелётных данных\"",
   "duration": "0,5",
   "url": "https://www.youtube.com/watch?v=ob8h2XnneXk",
   "tags": "hiload",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Андрей Козлов: Автоматизация тестирования веб-приложений с использованием Thucydides",
   "duration": "0,5",
   "url": "https://www.youtube.com/watch?v=l1Fcd-Fg-3A",
   "tags": "qa",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Егор Гилёв (Parcsis): \"Создание пользовательского интерфейса без программирования\"",
   "duration": "0,5",
   "url": "https://www.youtube.com/watch?v=Qt5_0xcAbNc",
   "tags": "",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Сергей Аверин (Badoo): \"MySQL+HandlerSocket=NoSQL\"",
   "duration": "0,5",
   "url": "https://www.youtube.com/watch?v=ecIB5X1M1Z8",
   "tags": "hiload",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Александр Родионов (Toptal): \"От Selenium к Watir — путь к просветлению\"",
   "duration": "0,5",
   "url": "https://www.youtube.com/watch?v=wQ4nwjpauO8",
   "tags": "qa",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Владимир Агафонкин: \"Высокопроизводительные визуализации данных в браузере\"",
   "duration": "0,5",
   "url": "https://www.youtube.com/watch?v=iCe4Nht-bmU",
   "tags": "frontend",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "François Reynaud (eBay): \"Tools for mobile automation are nothing special\"",
   "duration": "0,5",
   "url": "https://www.youtube.com/watch?v=GShYSh6pC2A",
   "tags": "qa",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Олег Мохов (Яндекс): \"Анимируй всё\"",
   "duration": "0,5",
   "url": "https://www.youtube.com/watch?v=ZUVfHumdpv8",
   "tags": "frontend",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Axel Rauschmayer: \"An overview of ECMAScript 6, the next version of JavaScript\"",
   "duration": "0,6",
   "url": "https://www.youtube.com/watch?v=qe_yOVPKkEk",
   "tags": "frontend",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Алексей Петров: \"Делаем прозрачными сроки тестирования методом черного ящика\"",
   "duration": "0,5",
   "url": "https://www.youtube.com/watch?v=OKmDO4PJv7A",
   "tags": "qa",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Matthew Mosesohn (Mirantis IT): \"Automating environments with Cobbler\"",
   "duration": "0,4",
   "url": "https://www.youtube.com/watch?v=tRLFNCiHED8",
   "tags": "qa",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Александр Хозя (Badoo): \"Как screenshot-based средство автоматизации нам помогает\"",
   "duration": "0,5",
   "url": "https://www.youtube.com/watch?v=JVagVmFq4xs",
   "tags": "qa",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Платон Днепровский (UIDG): \"Игровые механики в проектировании сервисов\"",
   "duration": "0,5",
   "url": "https://www.youtube.com/watch?v=InhRPYsA-vA",
   "tags": "",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Артём Ерошенко (Яндекс): \"Фреймворк Html Elements...\"",
   "duration": "0,5",
   "url": "https://www.youtube.com/watch?v=bQGF-BW3rNU",
   "tags": "frontend",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Александр Баяндин (2ГИС): \"JavaScript + Webdriver = ♥\"",
   "duration": "0,6",
   "url": "https://www.youtube.com/watch?v=8yuWnSSU66Y",
   "tags": "",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "CodeFest Mini 2012. Антон Спиридонов и Павел Мочалкин. Успехи и неудачи управления продуктами в 2ГИС",
   "duration": "0,6",
   "url": "https://www.youtube.com/watch?v=p9Jkk3LIufE",
   "tags": "управление проектами",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "CodeFest Mini 2012. Дмитрий Башакин. Управление рисками - это управление проектами для взрослыз",
   "duration": "0,7",
   "url": "https://www.youtube.com/watch?v=Umg8MlL748w",
   "tags": "управление проектами",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "В. Черницкий. Использование графических процессоров мобильных устройств",
   "duration": "0,5",
   "url": "https://www.youtube.com/watch?v=zlpsdDTqAA8",
   "tags": "",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Роман Бусыгин. Автосборки iOS-проектов в Яндексе",
   "duration": "0,5",
   "url": "https://www.youtube.com/watch?v=_XOxUAvosLw",
   "tags": "mobile",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Ольга Нечаева. Сбор статистики в мобильных играх с помощью сервиса Flurry",
   "duration": "0,6",
   "url": "https://www.youtube.com/watch?v=UxKHlEz7LYg",
   "tags": "",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Таисия Сибгатуллина. Тестирование мобильных приложений",
   "duration": "0,4",
   "url": "https://www.youtube.com/watch?v=iff35jPdeX0",
   "tags": "qa",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Сергей Белов. Пентест на стероидах. Автоматизируем процесс",
   "duration": "0,5",
   "url": "https://www.youtube.com/watch?v=1sdGNM73Ewc",
   "tags": "qa",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Сергей Быстрых. Карантинная зона для автотестов",
   "duration": "0,5",
   "url": "https://www.youtube.com/watch?v=ONcKZYi_AxQ",
   "tags": "qa",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Роман Ивлиев. Аккуратно переезжаем, или тестирование в проектах миграции",
   "duration": "0,5",
   "url": "https://www.youtube.com/watch?v=h1qtnz-mJ7U",
   "tags": "qa",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Александр Ильин. Метрики покрытия. Прагматичный подход",
   "duration": "0,6",
   "url": "https://www.youtube.com/watch?v=WPs2VHGc1Ss",
   "tags": "qa",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Дмитрий Анкудинов. О специфике мультиплатформенного тестирования игр",
   "duration": "0,5",
   "url": "https://www.youtube.com/watch?v=UtQqz9xR1X4",
   "tags": "qa",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Антон Сидельников. Опыт создания DSL на Ruby.",
   "duration": "0,4",
   "url": "https://www.youtube.com/watch?v=vQDAOM-1QmI",
   "tags": "",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Павел Шкарин. Отказоустойчивость или высокие нагрузки",
   "duration": "0,5",
   "url": "https://www.youtube.com/watch?v=lY35uEUq3NM",
   "tags": "hiload",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Катков Cергей. Бенчмарки как критерий естественного отбора",
   "duration": "0,5",
   "url": "https://www.youtube.com/watch?v=M95RILHFZ-k",
   "tags": "hiload",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Рычков Д. Про написание кеша",
   "duration": "0,3",
   "url": "https://www.youtube.com/watch?v=ZpyroiV58ks",
   "tags": "",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Иван Евтухович. Как мы делали Групон",
   "duration": "0,5",
   "url": "https://www.youtube.com/watch?v=s5HcEAR6THQ",
   "tags": "",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Сас А. Как слать 100М писем каждый день",
   "duration": "0,6",
   "url": "https://www.youtube.com/watch?v=jJJGdOiwisM",
   "tags": "hiload",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Титов А. Инженерный дзен",
   "duration": "0,5",
   "url": "https://www.youtube.com/watch?v=z3WtAIdVjIY",
   "tags": "",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Лихтер К. и Таратухин И. Коктейль «Skydive»",
   "duration": "0,5",
   "url": "https://www.youtube.com/watch?v=dHscQEyjeG4",
   "tags": "",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Павел Сташевский, Мета-тесты для авто-тестов",
   "duration": "0,4",
   "url": "https://www.youtube.com/watch?v=B1OPoamEyPw",
   "tags": "qa",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Сергей Быстрых, Карантинная зона для автотестов",
   "duration": "0,4",
   "url": "https://www.youtube.com/watch?v=4YqkhNbrjak",
   "tags": "qa",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Михаил Захаров, Разработка и внедрение на JavaScript",
   "duration": "0,5",
   "url": "https://www.youtube.com/watch?v=rAwE13EcyWE",
   "tags": "qa",
   "event": "CodeFest",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Андрей Ситник, Злые Марсиане | Используем PostCSS правильно | FrontTalks 2015",
   "duration": "0,6",
   "url": "https://www.youtube.com/watch?v=qhouBGNncGQ",
   "tags": "frontend",
   "event": "FrontTalks 2015",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Владимир Кузнецов, Graph | Глубокое погружение в webpack | FrontTalks 2015",
   "duration": "0,6",
   "url": "https://www.youtube.com/watch?v=IpCrjoDPrQQ",
   "tags": "frontend",
   "event": "FrontTalks 2015",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Александр Завьялов, Яндекс | Веб-анимация на JS и CSS | FrontTalks 2015",
   "duration": "0,6",
   "url": "https://www.youtube.com/watch?v=zJxPuXNHx_M",
   "tags": "frontend",
   "event": "FrontTalks 2015",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Тимофей Чаптыков, 2ГИС | Мейкап и контроль качества верстки | FrontTalks 2015",
   "duration": "0,6",
   "url": "https://www.youtube.com/watch?v=2TEcoNhk2wg",
   "tags": "frontend",
   "event": "FrontTalks 2015",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Вадим Макеев, Opera Software | О теге picture | FrontTalks 2014",
   "duration": "0,7",
   "url": "https://www.youtube.com/watch?v=7EhpWOkNfZg",
   "tags": "frontend",
   "event": "FrontTalks",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Владимир Кузнецов, Engine6 | Я ♥ SVG | FrontTalks 2014",
   "duration": "0,7",
   "url": "https://www.youtube.com/watch?v=BDXHS4N6LXk",
   "tags": "frontend",
   "event": "FrontTalks",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Арсений Форштретер, Яндекс | Гибкие коробки на практике | FrontTalks 2014",
   "duration": "0,7",
   "url": "https://www.youtube.com/watch?v=3j6v2rx1N1Y",
   "tags": "frontend",
   "event": "FrontTalks",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Роман Дворнов, Ostrovok.ru | Баба-Яга против! | FrontTalks 2014",
   "duration": "0,7",
   "url": "https://www.youtube.com/watch?v=ne8sxUxUiCA",
   "tags": "frontend",
   "event": "FrontTalks",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Алексей Бахирев, i-Free | Wap. Встройка. Мобильная разработка | FrontTalks 2014",
   "duration": "0,7",
   "url": "https://www.youtube.com/watch?v=b0r1b_hpkdA",
   "tags": "mobile",
   "event": "FrontTalks",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Алексей Иванов, JetStyle | О постпроцессорах и препроцессорах | FrontTalks 2014",
   "duration": "0,7",
   "url": "https://www.youtube.com/watch?v=xHP5-w7aw_0",
   "tags": "frontend",
   "event": "FrontTalks",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "SPA на Backbone ( FrontTalks - 23 ноября )",
   "duration": "0,5",
   "url": "https://www.youtube.com/watch?v=8c0vnlihiQ0",
   "tags": "frontend",
   "event": "FrontTalks",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "ymb и yms: асинхронные модули в JavaScript-проектах",
   "duration": "0,7",
   "url": "https://vimeo.com/141526235",
   "tags": "frontend",
   "event": "FrontTalks",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Docker в хозяйстве и быту",
   "duration": "",
   "url": "https://youtu.be/-67yNnx4bck",
   "tags": "devops",
   "event": "4front",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Docker & Puppet - как их скрестить и надо ли вам это",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=Gav_eQQKjKc",
   "tags": "",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Как мы переносим миллионы пользователей Badoo между дата-центрами",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=H_-QF5AFVKc",
   "tags": "",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Почему сложно программировать UI (Кирилл Мокевнин)",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=DCeNCr2tKOI",
   "tags": "frontend",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Интеллектуальная оптимизация CSS, Бен Бриггс про оптимизатор cssnano и PostCSS на dotCSS",
   "duration": "",
   "url": "http://www.thedotpost.com/2015/12/ben-briggs-intelligent-css-optimisation",
   "tags": "",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Organizing Your Company to Embrace Microservices",
   "duration": "1",
   "url": "http://www.infoq.com/presentations/500px-services",
   "tags": "hiload",
   "event": "посоветовали",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Доклад \"Docker в Badoo: от восторгов к внедрению\" на DevOps Meetup",
   "duration": "1",
   "url": "https://www.youtube.com/watch?v=jjNjAxX61F4",
   "tags": "devops",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Сказ о том, как инверсия зависимостей к DDD привела ",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=8KBbJcd-PEA",
   "tags": "software design",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Антон Бевзюк, TDD + DDD + MVP + GoF + PoEAA= Love! ",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=R8yfEe0Ur4M",
   "tags": "software design",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "DOMAIN DRIVEN DESIGN - КАК, ПОЧЕМУ И ЗАЧЕМ? ",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=rsg-Aa-d-_s",
   "tags": "software design",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "DDD: Реализуем проект «Вавилонская башня» - ",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=0q9B8v-SfUg",
   "tags": "software design",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "[DesignPatterns] 01. Стратегия - ",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=qo7Hqwypwcc",
   "tags": "software design",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "GoF Patterns + Rails =? Marat Kamenschykov ",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=ujIUX5IxdTE",
   "tags": "software design",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Андрей Бибичев, Обзор Feature-Driven Development и Domain-Driven Design - ",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=cFFyEuSn-h0",
   "tags": "software design",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Дмитрий Кандалов, Agile Object Oriented Design, SOLID Principle - ",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=av9ykUpscyk",
   "tags": "software design",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Принципы дизайна ООП (SOLID) ",
   "duration": "0,5",
   "url": "https://www.youtube.com/watch?v=OisLubIs3JA",
   "tags": "software design",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Математическое обоснование S.O.L.I.D принципов ",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=CmCEdVrZQAE",
   "tags": "software design",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Как писать красивый код или основы SOLID - ",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=bCvI7P2WPGA",
   "tags": "software design",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "Domain Driven Design. Плюсы и сложности.Часть 1 - ",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=hh5kC1Es4yk",
   "tags": "software design",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "DDD with Behat by Anton Serdyuk ",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=KO-spDn8cgg",
   "tags": "software design",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "SECON 2014 - DDD: от требований до кода (Максим Цепков) ",
   "duration": "",
   "url": "https://www.youtube.com/watch?v=XQUzFtyya2M",
   "tags": "software design",
   "event": "",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "«Docker в Badoo: ПМЖ или временная регистрация», Антон Турецкий, Badoo",
   "duration": "1",
   "url": "https://www.youtube.com/watch?v=i0Y6WV5XLAY",
   "tags": "devops",
   "event": "2016-07 https://habrahabr.ru/company/badoo/blog/304702/",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "“Проникновение в Docker с примерами”, Дмитрий Столяров, Flant",
   "duration": "1",
   "url": "https://www.youtube.com/watch?v=hdVNKmru3LM",
   "tags": "devops",
   "event": "2016-07 https://habrahabr.ru/company/badoo/blog/304702/",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "«Мониторь, автоматизируй Docker», Илья Раудсепп, Badoo",
   "duration": "0,5",
   "url": "https://www.youtube.com/watch?v=SlIvkmzwwvE",
   "tags": "devops",
   "event": "2016-07 https://habrahabr.ru/company/badoo/blog/304702/",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 },
 {
   "title": "“Сеть в Docker”, Константин Назаров, Parallels",
   "duration": "1",
   "url": "https://www.youtube.com/watch?v=HzD228hMdwY",
   "tags": "devops",
   "event": "2016-07 https://habrahabr.ru/company/badoo/blog/304702/",
   "date": "",
   "speakers": "",
   "language": "",
   "phash": ""
 }
];

